# --- Build stage ---
FROM node:22-slim AS builder
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/backend/package.json apps/backend/
COPY packages/shared/package.json packages/shared/
COPY tsconfig*.json ./

RUN pnpm install --frozen-lockfile

COPY apps/backend ./apps/backend
COPY packages/shared ./packages/shared

RUN pnpm --filter backend... build
RUN mkdir -p /app/uploads && chown -R 65532:65532 /app/uploads

RUN pnpm deploy --filter backend --prod /app/deploy

# --- Runtime stage ---
# FROM node:22-alpine
# WORKDIR /app

# COPY --from=builder /app/deploy ./
# COPY --from=builder /app/uploads ./uploads

# CMD ["node", "dist/server.js"]


FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /app

COPY --from=builder /app/deploy ./
COPY --from=builder /app/uploads ./uploads

USER nonroot
CMD ["dist/server.js"]