name: Build & Push Frontend

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  frontend-ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      app: frontend
