name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    secrets: inherit
    with:
      environment: prod
  # deploy-backend:
  #   needs: build-backend
  #   uses: ./.github/workflows/deploy-backend.yml
  #   secrets: inherit
  #   with:
  #     environment: prod
