name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
    with:
      environment: prod
