name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  # build-frontend:
  #   uses: ./.github/workflows/templates/build.yml
  #   secrets: inherit
  #   with:
  #     app: frontend
  push-frontend:
    # needs: build-frontend
    uses: ./.github/workflows/push-template.yml
    secrets: inherit
    with:
      service_name: ${{ vars.SERVICE_NAME }}
      app: frontend
      dockerfile: Dockerfile.frontend
      environment: prod
  deploy-frontend:
    needs: push-frontend
    uses: ./.github/workflows/deploy-frontend.yml
    secrets: inherit
    with:
      environment: prod
      container_image: ${{ needs.push-frontend.outputs.container_image }}
  # build-backend:
  #   uses: ./.github/workflows/build-backend.yml
  #   secrets: inherit
  #   with:
  #     environment: prod
  # deploy-backend:
  #   needs: build-backend
  #   uses: ./.github/workflows/deploy-backend.yml
  #   secrets: inherit
  #   with:
  #     environment: prod
  #     container_image: ${{ needs.build-backend.outputs.container_image }}
