name: Deploy Backend/Frontend
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app:
        description: "App to build (backend or frontend)"
        required: true
        type: string
      container_image:
        type: string
        required: true
      version:
        type: string
        required: true

env:
  TF_WORKING_DIR: ./infra/${{ inputs.app }}

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ vars.TF_S3 }}" \
            -backend-config="key=${{ vars.SERVICE_NAME }}/${{ inputs.environment }}/${{ inputs.app }}-tfstate"
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: "Terraform Plan (frontend)"
        if: inputs.app == 'frontend'
        run: |
          terraform plan -input=false \
            -var="service_name=${{ vars.SERVICE_NAME }}" \
            -var="app_name=${{ inputs.app }}" \
            -var="app_version=${{ inputs.version }}" \
            -var="env=${{ inputs.environment }}" \
            -var="backend_url=${{ vars.BACKEND_URL }}" \
            -var="backend_api_url=${{ vars.BACKEND_API_URL }}" \
            -var="container_image=${{ inputs.container_image }}" \
            -var="jwt_public_key=${{ vars.JWT_PUBLIC_KEY }}" \
            -var="domain_name=${{ vars.DOMAIN_NAME }}" \
            -var="public_sentry_dsn=${{ vars.PUBLIC_SENTRY_DSN }}" \
            -var="sentry_auth_token=${{ vars.SENTRY_AUTH_TOKEN }}" \
            -var="service_client_id=${{ vars.SERVICE_CLIENT_ID }}" \
            -var="service_client_secret=${{ vars.SERVICE_CLIENT_SECRET }}" \
            -out=tfplan_aws
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: "Terraform Plan (backend)"
        if: inputs.app == 'backend'
        run: |
          terraform plan -input=false \
            -var="service_name=${{ vars.SERVICE_NAME }}" \
            -var="app_name=${{ inputs.app }}" \
            -var="app_version=${{ inputs.version }}" \
            -var="env=${{ inputs.environment }}" \
            -var="base_url=${{ vars.BASE_URL }}" \
            -var="frontend_url=${{ vars.FRONTEND_URL }}" \
            -var="container_image=${{ inputs.container_image }}" \
            -var="domain_name=${{ vars.DOMAIN_NAME }}" \
            -out=tfplan_aws
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Save Terraform plan as text
        run: terraform show tfplan_aws > tfplan_aws.txt
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Upload Terraform Plan Text
        uses: actions/upload-artifact@v4
        with:
          name: tfplan_aws
          path: ${{ env.TF_WORKING_DIR }}/tfplan_aws.txt

      - name: "Terraform Apply"
        run: terraform apply -input=false -auto-approve tfplan_aws
        working-directory: ${{ env.TF_WORKING_DIR }}
