name: Deploy Backend

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      container_image:
        type: string
        required: true

env:
  TF_WORKING_DIR: ./infra/frontend

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ vars.TF_S3 }}" \
            -backend-config="key=${{ vars.SERVICE_NAME }}/${{ inputs.environment }}/frontend-tfstate"
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: "Terraform Plan"
        run: |
          terraform plan -input=false \
            -var="service_name=${{ vars.SERVICE_NAME }}" \
            -var="app_name=backend" \
            -var="env=${{ inputs.environment }}" \
            -out=tfplan_aws
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Save Terraform plan as text
        run: terraform show tfplan_aws > tfplan_aws.txt
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Upload Terraform Plan Text
        uses: actions/upload-artifact@v4
        with:
          name: tfplan_aws
          path: ${{ env.TF_WORKING_DIR }}/tfplan_aws.txt

      - name: "Terraform Apply"
        run: terraform apply -input=false -auto-approve tfplan_aws
        working-directory: ${{ env.TF_WORKING_DIR }}
