name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "apps/frontend/**"
      - "packages/shared/**"
      - Dockerfile.frontend
      - "infra/frontend/**"
      - ".github/workflows/**"
      - "!.github/workflows/backend.yml"
      - "!.github/workflows/deploy-backend.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/frontend/**"
      - "packages/shared/**"
      - Dockerfile.frontend
      - "infra/frontend/**"
      - ".github/workflows/**"
      - "!.github/workflows/backend.yml"
      - "!.github/workflows/deploy-backend.yml"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    secrets: inherit
    with:
      app: frontend

  push:
    needs: build
    uses: ./.github/workflows/push-template.yml
    secrets: inherit
    with:
      service_name: ${{ vars.SERVICE_NAME }}
      app: frontend
      dockerfile: Dockerfile.frontend
      environment: prod

  deploy:
    needs: push
    uses: ./.github/workflows/deploy-template.yml
    secrets: inherit
    with:
      environment: prod
      app: frontend
      container_image: ${{ needs.push.outputs.container_image }}
